apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: tekton-cart-pipeline-run-06
spec:
  serviceAccount: tekton-cart-service-account
  pipelineRef:
    name: tekton-cart-pipeline
  resources:
    - name: git-repo
      resourceRef:
        name: git-repo
    - name: image-registry
      resourceRef:
        name: image-registry
