apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-cart-git-repo
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/GandhiCloud/tekton-cart
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-cart-image-registry
spec:
  type: image
  params:
    - name: url
      # value: gandhicloud/tekton-cart
      # value: index.docker.io/gandhicloud/tekton-cart
      value: docker.io/gandhicloud/tekton-cart