apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tekton-cart-pipeline
spec:
  resources:
    - name: git-repo
      type: git
    - name: image-registry
      type: image
  tasks:
    - name: task-build-docker-image
      taskRef:
        name: build-docker-image
      params:
        - name: pathToDockerFile
          value: /workspace/git-repo/docker/Dockerfile
        - name: pathToContext
          value: /workspace/git-repo
      resources:
        inputs:
          - name: git-repo
            resource: git-repo
        outputs:
          - name: image-registry
            resource: image-registry
    - name: task-deploy-using-kubectl
      runAfter: [task-build-docker-image]  
      taskRef:
        name: deploy-using-kubectl
      resources:
        inputs:
          - name: git-repo
            resource: git-repo
      params:
        - name: pathToDeploymentFiles
          value: /workspace/git-repo/deployment/tekton-cart/