apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tekton-cart-pipeline
spec:
  resources:
    - name: git-repo
      type: git
    - name: image-registry
      type: image
  params:  
    - name: pathToDockerFile
      description: Path to Dockerfile
      default: /workspace/git-repo/docker/Dockerfile
    - name: pathToContext
      description: The build context used by Kaniko
      default: /workspace/git-repo
    - name: pathToDeploymentFiles
      description: kubectl yaml files
      default: "/workspace/git-repo/deployment/tekton-cart"
    - name: imageUrl
      description: Url of image repository
      default: "$(resources.image-registry.url)"
    - name: imageTag
      description: Tag of the images to be used.
      default: "latest"
  tasks:
    - name: task-build-docker-image
      taskRef:
        name: build-docker-image
      params:
        - name: pathToDockerFile
          value: "${params.pathToDockerFile}"
        - name: pathToContext
          value: "${params.pathToContext}"
        - name: imageUrl
          value: "${params.imageUrl}"
        - name: imageTag
          value: "${params.imageTag}"
      resources:
        inputs:
          - name: git-repo
            resource: git-repo
        outputs:
          - name: image-registry
            resource: image-registry
    - name: task-deploy-using-kubectl
      runAfter: [task-build-docker-image]  
      taskRef:
        name: deploy-using-kubectl
      params:
        - name: pathToDeploymentFiles
          value: "${params.pathToDeploymentFiles}"
        - name: imageUrl
          value: "${params.imageUrl}"
        - name: imageTag
          value: "${params.imageTag}"
      resources:
        inputs:
          - name: git-repo
            resource: git-repo
