apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-53
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/data
    type: ''
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle