apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image
spec:
  inputs:
    resources:
      - name: git-repo
        type: git
    params:
      - name: pathToDockerFile
        description: Path to Dockerfile
        default: /workspace/git-repo/docker/Dockerfile
      - name: pathToContext
        description: The build context used by Kaniko
        default: /workspace/git-repo
      - name: imageUrl
        description: Url of image repository
        default: "$(outputs.resources.image-registry.url)"
      - name: imageTag
        description: Tag of the images to be used.
        default: "latest"        
  outputs:
    resources:
      - name: image-registry
        type: image
  steps:
    - name: list-src1
      image: alpine
      command:
        - "echo"
      args:
        - "pathToDockerFile -> $(inputs.params.pathToDockerFile)" 
    - name: list-src2
      image: alpine
      command:
        - "echo"
      args:
        - "pathToContext -> $(inputs.params.pathToContext)" 
    - name: list-src3
      image: alpine
      command:
        - "echo"
      args:
        - "imageUrl -> $(inputs.params.imageUrl)" 
    - name: list-src4
      image: alpine
      command:
        - "echo"
      args:
        - "imageTag -> $(inputs.params.imageTag)" 
    - name: list-src5
      image: alpine
      command:
        - "ls"
      args:
        - "/workspace" 
    - name: list-src6
      image: alpine
      command:
        - "ls"
      args:
        - "/workspace/git-repo" 
    - name: list-src
      image: alpine
      command:
        - "ls"
      args:
        - "$(inputs.resources.git-repo.path)"
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.10.0
      env:
        - name: DOCKER_CONFIG
          value: /builder/home/.docker
      command:
        - /kaniko/executor
      args:
        - "--dockerfile=$(inputs.params.pathToDockerFile)"
        - "--destination=$(inputs.params.imageUrl):$(inputs.params.imageTag)"
        - "--context=$(inputs.params.pathToContext)"