apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-using-kubectl
spec:
  inputs:
    resources:
      - name: git-repo
        type: git
      - name: image-registry
        type: image
    params:
      - name: pathToDeploymentFiles
        description: Path to deployment yaml files
        default: /workspace/git-repo/deployment/tekton-cart/
      - name: imageUrl
        description: Url of image repository
        default: "$(inputs.resources.image-registry.url)"
      - name: imageTag
        description: Tag of the images to be used.
        default: "latest"
  steps:
    - name: update-yaml
    image: alpine
    command: ["sed"]
    args:
      - "-i"
      - "-e"
      - "s;__IMAGE__;${inputs.params.imageUrl}:${inputs.params.imageTag};g"
      - "${inputs.params.pathToDeploymentFiles}/02-deployment.yaml"
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(inputs.params.pathToDeploymentFiles)"
        - "--validate=false"